[package]
name = "majestic-refactored"
version = "0.4.3"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
chrono = "0.4.23"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
float-cmp = "0.9.0"
