refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{({l}):5.5} | {t}:{L} — {m}{n}"

root:
  level: off

loggers:
  majestic_refactored:
    level: trace
    appenders:
      - stdout
